name: CPython Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    env:
      pyversion: 3.14
      package_version: ${{ github.ref_name }}

    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@main

      - name: Fetch the externals
        run: get_externals.bat
        shell: cmd

      - name: Setup Python ${{ env.pyversion }}-x86
        id: py314x86
        uses: actions/setup-python@main
        with:
          python-version: ${{ env.pyversion }}
          architecture: x86
          update-environment: false

      - name: Setup Python ${{ env.pyversion }}-x64
        id: py314x64
        uses: actions/setup-python@main
        with:
          python-version: ${{ env.pyversion }}
          architecture: x64
          update-environment: false

      - name: Setup Python ${{ env.pyversion }}-arm64
        id: py314arm64
        uses: actions/setup-python@main
        with:
          python-version: ${{ env.pyversion }}
          architecture: arm64
          update-environment: false

      - name: Set up Visual Studio x86 shell
        uses: egor-tensin/vs-shell@master
        with:
          arch: x86

      # Build for all 3 arches on the exes and the C extension for each wheel.
      - name: Build the exes
        run: |
          msbuild ".\pcbuild\pcbuild.sln" /p:Configuration=Release /p:Platform=Win32
          msbuild ".\pcbuild\pcbuild.sln" /p:Configuration=Release /p:Platform=x64
          msbuild ".\pcbuild\pcbuild.sln" /p:Configuration=Release /p:Platform=arm64
        shell: pwsh

      - name: Build the sdist and wheel
        run: |
          $env:PATH = "${{ env.RUNNER_TOOL_CACHE }}\Python\3.14.2\x86\Scripts;$env:PATH"
          ${{ steps.py314x86.outputs.python-path }} -m pip install --upgrade build wheel meson-python meson ninja
          ${{ steps.py314x86.outputs.python-path }} -m build --sdist --wheel --no-isolation
        shell: pwsh

      - name: Audit the wheels
        run: ${{ steps.py314arm64.outputs.python-path }} -m audit_wheel
        shell: pwsh

      - name: Upload dist folder
        uses: actions/upload-artifact@main
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@main

      - name: Restore dist folder artifacts
        uses: actions/download-artifact@main
        with:
          path: dist/
          pattern: release-dists
          merge-multiple: true

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
