name: CPython

on:
  push:
    tags:
      - '*'

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # x86 build on x64 host
          - os: windows-latest
            pyversion: 3.14
            arch: x86
            py_platform_tag: win32
            py_python_tag: cp314
            package_version: ${{ GITHUB_REF_NAME }}
          # x64 build on x64 host
          - os: windows-latest
            pyversion: 3.14
            arch: x64
            py_platform_tag: win_amd64
            py_python_tag: cp314
            package_version: ${{ GITHUB_REF_NAME }}
          # arm64 build on arm64 host
          - os: windows-11-arm
            pyversion: 3.14
            arch: arm64
            py_platform_tag: win_arm64
            py_python_tag: cp314
            package_version: ${{ GITHUB_REF_NAME }}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main

      - name: Fetch the externals
        run: get_externals.bat
        shell: cmd

      - name: Setup Python ${{ matrix.pyversion }}
        uses: actions/setup-python@main
        with:
          python-version: ${{ matrix.pyversion }}
          architecture: ${{ matrix.arch }}

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@master
        with:
          arch: ${{ matrix.arch }}

      - name: Build the project (with sdist and wheel)
        run: |
          python3 -m pip install --upgrade build wheel meson-python meson ninja
          python3 -m build --sdist --wheel --no-isolation
        shell: pwsh

      - name: retag the wheel
        run: |
          wheel tags dist/py2exestub-${{ matrix.package_version }}-${{ matrix.py_python_tag }}-abi3-${{ matrix.py_platform_tag }}.whl --python-tag py3 --abi-tag none --platform-tag ${{ matrix.py_platform_tag }}
          del dist/py2exestub-${{ matrix.package_version }}-${{ matrix.py_python_tag }}-abi3-${{ matrix.py_platform_tag }}.whl
        shell: pwsh

      - name: Upload dist folder
        uses: actions/upload-artifact@main
        with:
          name: release-dists-${{ matrix.arch }}
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
    steps:
      - uses: actions/checkout@main

      - name: Restore dist folder artifacts
        uses: actions/download-artifact@main
        with:
          path: dist/
          pattern: release-dists-*
          merge-multiple: true

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
